# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "avocado"
darkMode = "auto"
darkToggle = true
# logo = "pfp.png"
# description = "My awesome website"
# mainSections = ["section1", "section2"]
# robots = ""

[homepage]
  layout = "custom" # valid options: page, profile, custom
  showRecent = false
  showBio = true

[article]
  showDate = true
  dateFormat = "January 2, 2006"
  showAuthor = false
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = false
  showWordCount = false
  # sharingLinks = ["facebook", "twitter", "pinterest", "reddit", "linkedin", "email"]

[list]
  showBreadcrumbs = false
  showSummary = true
  groupByYear = false

[taxonomy]
  showTermCount = true

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
